repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2 # Changed to stable version
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        args: ["run", "--timeout=5m", "./cmd/..."]
        types: [go]
        language: system
        pass_filenames: false

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: ["-x"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c 'cd cmd && gofmt -s -w .'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: bash -c 'cd cmd && go vet .'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-imports
        name: go imports
        entry: bash -c 'cd cmd && (command -v goimports >/dev/null 2>&1 && goimports -w . || echo "goimports not installed, skipping")'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-unit-tests
        name: go test
        entry: bash -c 'cd cmd && go test -v .'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-build
        name: go build
        entry: ./build-local.sh --quick
        language: system
        types: [go]
        pass_filenames: false
