name: Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            arch: amd64
            output: credential-masker-linux-amd64
          - os: linux
            arch: arm64
            output: credential-masker-linux-arm64
          - os: darwin
            arch: amd64
            output: credential-masker-darwin-amd64
          - os: darwin
            arch: arm64
            output: credential-masker-darwin-arm64
          - os: windows
            arch: amd64
            output: credential-masker-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Verify Go modules
      - name: Verify Go modules
        run: |
          go mod tidy
          go mod verify

      # Build binary for all platforms
      - name: Build binary for ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
        run: |
          # Disable CGO for cross-compilation
          CGO_ENABLED=0 GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} go build -o ${{ matrix.platform.output }} ./cmd

      # Upload artifact for testing/verification
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.output }}
          path: ${{ matrix.platform.output }}
          retention-days: 5
