name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false  # Prevent all jobs from failing if one fails
      matrix:
        platform:
          - os: linux
            arch: amd64
            output: credential-masker-linux-amd64
          - os: linux
            arch: arm64
            output: credential-masker-linux-arm64
          - os: darwin
            arch: amd64
            output: credential-masker-darwin-amd64
          - os: darwin
            arch: arm64
            output: credential-masker-darwin-arm64
          - os: windows
            arch: amd64
            output: credential-masker-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Verify Go modules first
      - name: Verify Go modules
        run: |
          go mod tidy
          go mod verify

      # Fix for the issue when building for Windows
      - name: Build binary
        run: |
          # Disable CGO for cross-compilation
          CGO_ENABLED=0 GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} go build -o ${{ matrix.platform.output }} ./cmd

      # Update to v4 of the upload artifact action
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.output }}
          path: ${{ matrix.platform.output }}

  create-release:
    needs: build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Update to v4 of the download artifact action
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      # Fix artifact paths
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            credential-masker-linux-amd64/credential-masker-linux-amd64
            credential-masker-linux-arm64/credential-masker-linux-arm64
            credential-masker-darwin-amd64/credential-masker-darwin-amd64
            credential-masker-darwin-arm64/credential-masker-darwin-arm64
            credential-masker-windows-amd64.exe/credential-masker-windows-amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true
