name: Verify PR

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Verify Go modules 
      - name: Verify Go modules
        run: |
          go mod tidy
          go mod verify

      # Run tests if you have them
      - name: Run tests
        run: go test -v ./...

      # Verify build works for at least one platform
      - name: Verify build
        run: go build -o credential-masker ./cmd
